// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/diary_core/model.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `recovery_summary`, `wired_capabilities`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeSession>>
abstract class BridgeSession implements RustOpaqueInterface {
  /// 取消后续处理；不删除任何原件。
  Future<SearchSnapshot> cancelSearch({required String sessionId});

  /// 已经接到桥上的契约方法名。
  Future<List<String>> capabilities();

  /// 提交记录，创建原始文字版本。
  Future<CommitResult> commit({
    required String captureId,
    required PlatformInt64 expectedRevision,
    required String operationId,
  });

  /// 创建草稿，契约第 4.1 节 `captures.createDraft`。
  Future<Capture> createDraft({
    DateTime? occurredAt,
    required String timeZone,
    required int utcOffsetMinutes,
    required String operationId,
  });

  /// 从某个序号之后读取持久业务事件。
  Future<List<DomainEvent>> eventsSince({required PlatformInt64 fromSequence});

  /// 对某个来源（来源 id 或修订 id 都行）跑一次提取。
  Future<ExtractedContent> extractSource({required String sourceRef});

  /// 读取某个来源当前版本的派生内容；没提取过时返回空。
  Future<ExtractedContent?> extractedContent({required String sourceId});

  /// 声明复制完成。核心会自己重算哈希并比对。
  Future<ImportStatus> finishImport({
    required String importId,
    required String stagingTicket,
    required ImportManifest manifest,
  });

  Future<Capture> getCapture({required String captureId});

  Future<Job> getJob({required String jobId});

  Future<ImportStatus> importStatus({required String importId});

  /// 索引覆盖状态，契约第 4.4 节 `indexes.status`。
  ///
  /// `source_scope` 为空表示整个资料库；空数组是「什么都不看」而不是「看全部」。
  Future<IndexStatus> indexStatus({List<String>? sourceScope});

  /// 核心信息与恢复摘要。
  Future<LibraryInfo> info();

  /// 分页读取记录。cursor 对调用方不透明。
  Future<CapturePage> listCaptures({
    String? dayKey,
    String? cursor,
    required int limit,
  });

  /// 按状态列出任务；不传状态就列全部。
  Future<List<Job>> listJobs({List<JobState>? states, required int limit});

  /// 把 sourceRef + locator 解析成可打开的原件与可用性。
  Future<SourceLocation> locateSource({
    required String sourceRef,
    required SourceLocator locator,
  });

  /// 建议的下次唤醒时刻；没有待办时为空。
  Future<DateTime?> nextWakeup();

  /// 打开（或创建）资料库。
  static Future<BridgeSession> open({required String libraryPath}) =>
      RustLib.instance.api.crateApiBridgeSessionOpen(libraryPath: libraryPath);

  /// 申请导入暂存位置。平台层只能往票据指向的文件里写。
  Future<ImportTicket> prepareImport({
    required String captureId,
    required String displayName,
    String? mimeHint,
    PlatformInt64? sizeHint,
    required ImportOrigin origin,
    required String operationId,
  });

  /// 取某个来源**当前修订的父修订**（上一版正文），供界面「看原正文」用。
  ///
  /// 没有上一版时返回空。返回的是修订，不是 diff：差在哪由前端算。
  /// 父修订可能是原件型修订（`text` 为空、`asset_id` 有值），前端要按这个分支
  /// 决定是显示文字还是提供「打开原件」。
  Future<SourceRevision?> previousSourceRevision({required String sourceId});

  /// 修改某一篇来源的原始文字：新建一个修订，旧修订保留。
  ///
  /// 契约第 4.1 节 `sources.reviseText`。**改完必须再跑一次 `extract_source`**，
  /// 新修订才会进索引——这一步不自动做（提取有自己的失败与重试语义，见
  /// `docs/architecture/m2-修订与检索可见性.md`）。
  Future<SourceRevision> reviseText({
    required String sourceId,
    required String text,
    required PlatformInt64 expectedRevision,
    required String operationId,
  });

  /// 保存草稿。只有核心确认落盘后才返回 `durable = true`。
  Future<DraftSaveResult> saveDraft({
    required String captureId,
    required String text,
    required PlatformInt64 expectedRevision,
    required String operationId,
  });

  /// 翻页；`cursor` 为空表示接着当前进度。游标不属于这个会话报 `cursor_expired`。
  Future<SearchSnapshot> searchNextPage({
    required String sessionId,
    String? cursor,
  });

  /// 读当前快照；会话不存在或索引变了报 `search_expired`。
  Future<SearchSnapshot> searchSnapshot({required String sessionId});

  /// 发起一次检索，契约第 4.4 节 `search.start`。
  Future<SearchSnapshot> startSearch({
    required SearchRequest request,
    required PlatformInt64 queryRevision,
  });
}

/// 桥接错误：`code` 是契约第 7 节的错误码，`message` 给用户看。
///
/// frb 会把它变成 Dart 侧的异常类型，所以前端可以用 `on BridgeError catch (e)`
/// 直接读 `e.code`。
class BridgeError implements FrbException {
  final String code;
  final String message;
  final bool retryable;

  const BridgeError({
    required this.code,
    required this.message,
    required this.retryable,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ retryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          retryable == other.retryable;
}

/// 核心信息与恢复摘要。
class LibraryInfo {
  final String apiVersion;
  final PlatformInt64 dataSchemaVersion;
  final String buildVersion;
  final String libraryId;

  /// 已经接到桥上的契约方法名。**没列出来的就是还没接**，界面据此决定哪些入口可见。
  final List<String> capabilities;
  final RecoverySummary recovery;

  /// 记录数量（不含回收站），契约 `CoreSnapshot.captureCount`。
  final PlatformInt64 captureCount;

  /// 事件表里最大的序号，契约 `CoreSnapshot.lastEventSequence`；没有事件时为 0。
  final PlatformInt64 lastEventSequence;

  const LibraryInfo({
    required this.apiVersion,
    required this.dataSchemaVersion,
    required this.buildVersion,
    required this.libraryId,
    required this.capabilities,
    required this.recovery,
    required this.captureCount,
    required this.lastEventSequence,
  });

  @override
  int get hashCode =>
      apiVersion.hashCode ^
      dataSchemaVersion.hashCode ^
      buildVersion.hashCode ^
      libraryId.hashCode ^
      capabilities.hashCode ^
      recovery.hashCode ^
      captureCount.hashCode ^
      lastEventSequence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryInfo &&
          runtimeType == other.runtimeType &&
          apiVersion == other.apiVersion &&
          dataSchemaVersion == other.dataSchemaVersion &&
          buildVersion == other.buildVersion &&
          libraryId == other.libraryId &&
          capabilities == other.capabilities &&
          recovery == other.recovery &&
          captureCount == other.captureCount &&
          lastEventSequence == other.lastEventSequence;
}

/// 打开资料库后的恢复摘要。数字都是真实统计，不是估计。
class RecoverySummary {
  /// 上次没走完的导入数量。
  final int recoverableImports;

  /// 上次没走完的录音数量。
  final int openRecordings;

  /// 还没做完的任务数量。
  final int pendingJobs;
  final List<String> notes;

  const RecoverySummary({
    required this.recoverableImports,
    required this.openRecordings,
    required this.pendingJobs,
    required this.notes,
  });

  @override
  int get hashCode =>
      recoverableImports.hashCode ^
      openRecordings.hashCode ^
      pendingJobs.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoverySummary &&
          runtimeType == other.runtimeType &&
          recoverableImports == other.recoverableImports &&
          openRecordings == other.openRecordings &&
          pendingJobs == other.pendingJobs &&
          notes == other.notes;
}
