// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `snapshot_for`

/// 事件流探针：按序号发 `count` 条事件后关闭流。
///
/// 用来验证契约第 6 节要求的「从快照开始订阅、按序号去重」这条链路在桥接上成立。
/// 真实实现会用持久业务事件替换它。
Stream<ProbeEvent> watchProbeEvents({required int count}) =>
    RustLib.instance.api.crateApiWatchProbeEvents(count: count);

/// 打开或创建资料库（同步路径）。
///
/// `library_handle` 为空表示使用默认库。M0 只返回结构，不碰磁盘。
Future<CoreSnapshot> open({String? libraryHandle}) =>
    RustLib.instance.api.crateApiOpen(libraryHandle: libraryHandle);

/// 打开或创建资料库（异步路径）。
///
/// 与 [`open`] 返回同样的结构，用来验证 Dart 侧的 Future 是否正常完成。
Future<CoreSnapshot> openAsync({String? libraryHandle}) =>
    RustLib.instance.api.crateApiOpenAsync(libraryHandle: libraryHandle);

/// 轻量启动快照。
Future<CoreSnapshot> snapshot() => RustLib.instance.api.crateApiSnapshot();

/// 一个可判定的纯计算函数：验证跨语言调用的参数与返回值没有走样。
Future<int> add({required int a, required int b}) =>
    RustLib.instance.api.crateApiAdd(a: a, b: b);

/// 回显文本，用于验证中文与 emoji 在桥接两侧保持一致。
Future<String> echo({required String text}) =>
    RustLib.instance.api.crateApiEcho(text: text);

/// 契约第 1.3 节：核心与协议的版本信息。
class CoreInfo {
  /// 主次版本；新增可选字段是次版本，删除或改变语义是主版本。
  final String apiVersion;
  final int dataSchemaVersion;
  final String buildVersion;
  final String libraryId;

  /// 当前构建实际支持的能力，界面据此决定哪些入口可见。
  final List<String> capabilities;

  const CoreInfo({
    required this.apiVersion,
    required this.dataSchemaVersion,
    required this.buildVersion,
    required this.libraryId,
    required this.capabilities,
  });

  @override
  int get hashCode =>
      apiVersion.hashCode ^
      dataSchemaVersion.hashCode ^
      buildVersion.hashCode ^
      libraryId.hashCode ^
      capabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreInfo &&
          runtimeType == other.runtimeType &&
          apiVersion == other.apiVersion &&
          dataSchemaVersion == other.dataSchemaVersion &&
          buildVersion == other.buildVersion &&
          libraryId == other.libraryId &&
          capabilities == other.capabilities;
}

/// 轻量启动快照，不返回整库正文或媒体。
class CoreSnapshot {
  final CoreInfo coreInfo;
  final RecoverySummary recovery;
  final int pendingJobCount;
  final BigInt lastEventSequence;
  final int captureCount;

  const CoreSnapshot({
    required this.coreInfo,
    required this.recovery,
    required this.pendingJobCount,
    required this.lastEventSequence,
    required this.captureCount,
  });

  @override
  int get hashCode =>
      coreInfo.hashCode ^
      recovery.hashCode ^
      pendingJobCount.hashCode ^
      lastEventSequence.hashCode ^
      captureCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreSnapshot &&
          runtimeType == other.runtimeType &&
          coreInfo == other.coreInfo &&
          recovery == other.recovery &&
          pendingJobCount == other.pendingJobCount &&
          lastEventSequence == other.lastEventSequence &&
          captureCount == other.captureCount;
}

/// 契约第 6 节：事件流探针用的事件对象。
class ProbeEvent {
  /// 单调递增的序号，对应契约里的事件游标。
  final int sequence;
  final String message;

  const ProbeEvent({required this.sequence, required this.message});

  @override
  int get hashCode => sequence.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProbeEvent &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          message == other.message;
}

/// 启动恢复摘要：如实告知上次发生了什么。
class RecoverySummary {
  final int recoveredDraftCount;
  final int orphanedImportCount;
  final int unrecoveredRecordingCount;
  final List<String> notes;

  const RecoverySummary({
    required this.recoveredDraftCount,
    required this.orphanedImportCount,
    required this.unrecoveredRecordingCount,
    required this.notes,
  });

  @override
  int get hashCode =>
      recoveredDraftCount.hashCode ^
      orphanedImportCount.hashCode ^
      unrecoveredRecordingCount.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoverySummary &&
          runtimeType == other.runtimeType &&
          recoveredDraftCount == other.recoveredDraftCount &&
          orphanedImportCount == other.orphanedImportCount &&
          unrecoveredRecordingCount == other.unrecoveredRecordingCount &&
          notes == other.notes;
}
