// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class F64Array4 extends NonGrowableListView<double> {
  static const arraySize = 4;

  @internal
  Float64List get inner => _inner;
  final Float64List _inner;

  F64Array4(this._inner) : assert(_inner.length == arraySize), super(_inner);

  F64Array4.init() : this(Float64List(arraySize));
}
